# Generated by Django 4.0.6 on 2022-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=350, verbose_name='ticket')),
                ('period', models.CharField(max_length=2, verbose_name='period')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('open', models.DecimalField(decimal_places=10, max_digits=10)),
                ('high', models.DecimalField(decimal_places=10, max_digits=10)),
                ('low', models.DecimalField(decimal_places=10, max_digits=10)),
                ('close', models.DecimalField(decimal_places=10, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
    ]
